### ISSUE TITLE
Set flambe function memory to 128 MB

### ISSUE THREAD

**Issue by chris-feist** [icarus-sullivan/serverless-plugin-flambe#2]
Currently the `flambe` lambda gets deployed with the project's memorySize that is defined in the `serverless.yml` file. 

However, some projects may use higher default memory sizes for their lambdas.

Since the `flambe` lambda just invokes the other lambdas, it has a very small memory requirement and should have a small default `memorySize`, like 128 MB.

**Comment by icarus-sullivan** [comment]
@chris-feist Thanks for the great feedback as always. I rolled the additional option for a memorySize into the v3 of this library. [PR](https://github.com/icarus-sullivan/serverless-plugin-flambe/pull/3).

Please give the latest 0.1.0 version a try, however it is a minor change and therefor breaks previous flambe definitions. Unless no custom declaration was created.

**Comment by icarus-sullivan** [comment]
Also, please let me know how the migration goes for you so I can resolve this issue.

**Comment by icarus-sullivan** [comment]
Adding in 0.1.1, closing this.

**Comment by chris-feist** [comment]
Everything looks good! Thanks for the quick turnaround 👍
